# Generated by Django 5.1.2 on 2024-11-11 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('citizenship', models.CharField(max_length=20)),
                ('search_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('id_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='sa_id_app.idinfo')),
            ],
        ),
    ]
